### ISSUE TITLE
not working for large obj files 

### ISSUE THREAD

**Issue by ujjwal-kumar19** [astaka-pe/Dual-DMP#7]
I have used a obj file of 6.8 MB and 22 MB noisemaker.py is exiting without any error.

**Comment by astaka-pe** [comment]
@ujjwalinvent 
A mesh with 22 MB seems to be too large. How many vertices does each mesh have? Also, could you please share both meshes?

**Comment by ujjwal-kumar19** [comment]
I am uploading a 6.2 MB mesh its also not working for this. I debugged the code there seems to be some memory allocation problem.
the problem seems to be in self.build_v2v() in mesh.py constructor
[4_half.zip](https://github.com/astaka-pe/Dual-DMP/files/11364900/4_half.zip)

**Comment by astaka-pe** [comment]
@ujjwalinvent 
The "eye-glass" model seems already noisy, but do you still want to add more noise, right?
I tested both `noisemaker.py` (noise level = 0.3) and `main4real.py`, and they worked fine on my end.

![snapshot00_L00](https://user-images.githubusercontent.com/64598460/235445754-e0d794c0-b301-4f76-81e4-59d072fc0aab.png)
![snapshot00_L01](https://user-images.githubusercontent.com/64598460/235445779-dfd87c27-cef4-48ee-80dd-b2cbc33b3b5a.png)

**Comment by ujjwal-kumar19** [comment]
Okay I am a bit confused here, what is the way to remove the noise for a mesh we don't have the ground truth, as per the documentation I ran the noisemaker for noisy mesh it generated 3 obj files and then ran main4real.py. Am I doing something wrong here?

**Comment by astaka-pe** [comment]
@ujjwalinvent 
The `noisemaker.py` is a script to generate an artificial noisy mesh, which you don't need to run here.
Place your own model into `datasets/eye-glass/eye-glass.obj` ("eye-glass" can be replaced by any name),
and run
`python preprocess/preprocess.py -i datasets/eye-glass`
for preprocessing.
Finally, run
`python main4real.py -i datasets/eye-glass`
for denoising.

The figure below shows the result of the experiment on my end.

![snapshot00_L01](https://user-images.githubusercontent.com/64598460/235449413-669ab19d-3e49-49d5-bb01-d48abf607a26.png)
![snapshot00_L00](https://user-images.githubusercontent.com/64598460/235449398-b4b9a091-471b-4779-b1f9-75207f213788.png)

**Comment by ujjwal-kumar19** [comment]
`    def build_v2v(self):
        """ compute adjacent matrix """
        edges = self.edges
        v2v_inds = edges.T
        v2v_inds = torch.from_numpy(np.concatenate([v2v_inds, v2v_inds[[1, 0]]], axis=1)).long()
        v2v_vals = torch.ones(v2v_inds.shape[1]).float()
        self.v2v_mat = torch.sparse.FloatTensor(v2v_inds, v2v_vals, size=torch.Size([len(self.vs), len(self.vs)]))
        self.v_dims = torch.sum(self.v2v_mat.to_dense(), axis=1)
`
this is a snippet from mesh.py the last line of this function is crashing due to lack of memory, are you using high memory on your machine like 16GB/32 GB RAM and GPU, I have 70000 vertices it is creating a matrix of 70k * 70k that is a huge matrix, isn't this issue for the code?

**Comment by astaka-pe** [comment]
@ujjwalinvent 
As described in the [paper](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136630358.pdf) (4. Experiments), we used a PC with NVIDIA GeForce TITAN X (12 GB graphics memory) and 64 GB RAM.
This sparce matrix is necessary for computing the [loss function](https://github.com/astaka-pe/Dual-DMP/blob/ef2f0750325c1c8ade9c925896b122a3bcd1b6b3/util/loss.py#L37).

**Comment by ujjwal-kumar19** [comment]
![error_colab](https://user-images.githubusercontent.com/1160664/235635025-5a00ec92-72fc-4dd7-bb0d-95efd9d2f2af.PNG)
Check the attached image I have done exactly you said but preprocess.py is giving error.

**Comment by astaka-pe** [comment]
Sorry for any confusion.
For preprocessing, please run
`python preprocess/preprocess.py -i datasets/spacs6`
Please note that this scripts may generate the following error message:
`FileNotFoundError: [Errno 2] No such file or directory: 'datasets/spacs6/spacs6_gt.obj'`.
However, this error is not a problem if you successfully generate `spacs6_noise.obj` and `spacs6_smooth.obj`.
(We will update this issue as soon as possible.)

**Comment by ujjwal-kumar19** [comment]
as I understand the code the file inside the folder specs6 should have a name spec6_noise.obj and preprocessor.py will generate spec6_smooth.obj this is working fine for now. and then I should call main4real.py which will work without _gt file?

also doing the following change in the code in mesh.py 
in build_v2v() fixes memory problems
        #self.v_dims = torch.sum(self.v2v_mat.to_dense(), axis=1)
        self.v_dims = torch.sparse.sum(self.v2v_mat, dim=1).to_dense()
while retaining the same functionality.

**Comment by astaka-pe** [comment]
@ujjwalinvent Yes, `main4real.py` works without a ground-truth mesh.

**Comment by ujjwal-kumar19** [comment]
before main4real.py you are doing a transformation to meshes that normalizes the meshes, is there a way to obtain the output mesh in the same coordinate system as the original input without any transformation applied?

**Comment by astaka-pe** [comment]
@ujjwalinvent 
There is currently no available transformation script for that purpose. However, if you retain the translation vector and scaling factor that were applied during the normalization process, you can convert it back to the original coordinate system.

You may need to modify the normalization script yourself in order to retain the transformation information. We use pymeshlab's filters in our script, which include:
- [transform_scale_normalize](https://pymeshlab.readthedocs.io/en/2021.10/filter_list.html#transform_scale_normalize)
- [transform_translate_center_set_origin](https://pymeshlab.readthedocs.io/en/2021.10/filter_list.html#transform_translate_center_set_origin)
